# Generated by Django 6.0.3 on 2026-03-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliosnapshot',
            name='symbol',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
